"""
Full RAG pipeline orchestration for the Self-Improving RAG system.

Integrates retrieval, reranking, generation, and storage into a single
async function that powers the UI and CLI.
"""

import logging
import time
from typing import List, Optional

import numpy as np

from self_improving_rag.core.config import RETRIEVE_K, RERANK_TOP_N
from self_improving_rag.core.exceptions import RAGException
from self_improving_rag.storage.db import init_db
from self_improving_rag.storage.queries import insert_session, insert_retrievals_batch
from self_improving_rag.retrieval.ingest import embed_query
from self_improving_rag.retrieval.retriever import retrieve
from self_improving_rag.reranker.inference import rerank
from self_improving_rag.reranker.registry import registry
from self_improving_rag.generation.prompt import format_prompt
from self_improving_rag.generation.llm import generate_response
from self_improving_rag.generation.citations import map_citations_to_chunks
from self_improving_rag.generation.response import RAGResponse
from self_improving_rag.evaluation.ab_test import ABTester

logger = logging.getLogger(__name__)


async def run_pipeline(
    query: str,
    session_id: Optional[str] = None,
    force_model: Optional[str] = None
) -> RAGResponse:
    """
    Execute the full end-to-end RAG workflow.

    Flow:
    1. Embed query
    2. Retrieve top-K chunks from FAISS
    3. Rerank top-N chunks using CrossEncoder (A/B tested)
    4. Generate factual answer with citations via LLM
    5. Log session and retrievals to DB
    6. Return structured RAGResponse

    Args:
        query: User's question.
        session_id: Optional UUID (generated if not provided).
        force_model: Optional registry name to bypass A/B testing.

    Returns:
        RAGResponse: Final answer with cited sources.

    Raises:
        RAGException: If any stage of the pipeline fails.
    """
    start_time = time.time()
    
    try:
        # 0. Initialize DB if not already done
        await init_db()

        # 1. Embed query (needed for both FAISS and DB)
        query_vec = embed_query(query)

        # 2. Retrieval (Top-K candidates)
        t0 = time.time()
        retrieved_chunks = retrieve(query, k=RETRIEVE_K, precomputed_embedding=query_vec)
        logger.info(f"Retrieval took {time.time() - t0:.2f}s")

        # 3. Reranking (A/B Route or Forced)
        t0 = time.time()
        temp_sid = session_id or "internal_temp"
        active_model_name = force_model or ABTester.route_reranker(temp_sid)
        
        # Swap registry if needed
        if registry.get_active_config().name != active_model_name:
            registry.set_active(active_model_name)

        reranked_chunks = rerank(query, retrieved_chunks, top_n=RERANK_TOP_N)
        logger.info(f"Reranking took {time.time() - t0:.2f}s using {active_model_name}")

        # 4. Generation
        t0 = time.time()
        prompt = format_prompt(query, reranked_chunks)
        answer = await generate_response(prompt)
        logger.info(f"Generation took {time.time() - t0:.2f}s")

        # 5. Parsing & Citations
        cited_chunks = map_citations_to_chunks(answer, reranked_chunks)

        # 6. Persistence
        # Store using the provided session_id or a new one generated by insert_session
        actual_session_id = await insert_session(query, query_vec.tobytes(), session_id=session_id)
        
        # Log all reranked chunks (what was shown or considered top)
        await insert_retrievals_batch(actual_session_id, reranked_chunks)

        # 7. Response Building
        elapsed = time.time() - start_time
        response = RAGResponse(
            session_id=actual_session_id,
            query=query,
            answer=answer,
            cited_chunks=cited_chunks,
            all_retrieved_chunks=reranked_chunks,
            metadata={
                "model_name": active_model_name,
                "latency_sec": round(elapsed, 3),
                "retrieved_count": len(retrieved_chunks),
                "reranked_count": len(reranked_chunks),
            }
        )

        logger.info(f"Pipeline run complete in {elapsed:.2f}s for query: '{query[:50]}'")
        return response

    except Exception as exc:
        logger.error(f"Pipeline failed: {exc}", exc_info=True)
        if isinstance(exc, RAGException):
            raise
        raise RAGException(f"Pipeline execution error: {exc}") from exc
